version: '3.5'
services:
  postgresql:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: qore
      POSTGRES_USER: qore
      POSTGRES_PASSWORD: qore
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - backend
    restart: on-failure
    volumes:
      - ${PWD}/db/data:/var/lib/postgresql/data

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge